mSet<-InitDataObjects("conc", "stat", FALSE)
mSet<-Read.TextData(mSet, "Replacing_with_your_file_path", "rowu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-RemoveMissingPercent(mSet, percent=0.5)
mSet<-ImputeMissingVar(mSet, method="min")
mSet<-FilterVariable(mSet, "rsd", "F", 25)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "MedianNorm", "LogNorm", "ParetoNorm", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)
mSet<-FC.Anal.unpaired(mSet, 2.0, 0)
mSet<-PlotFC(mSet, "fc_0_", "png", 72, width=NA)
mSet<-Ttests.Anal(mSet, F, 0.05, FALSE, TRUE, FALSE)
mSet<-PlotTT(mSet, "tt_0_", "png", 72, width=NA)
mSet<-Ttests.Anal(mSet, T, 0.05, FALSE, TRUE, FALSE)
mSet<-PlotTT(mSet, "tt_1_", "png", 72, width=NA)
mSet<-Volcano.Anal(mSet, FALSE, 2.0, 0, 0.75,F, 0.1, TRUE, "raw")
mSet<-PlotVolcano(mSet, "volcano_0_",1, "png", 72, width=NA)
mSet<-Volcano.Anal(mSet, FALSE, 1.5, 0, 0.75,F, 0.1, TRUE, "fdr")
mSet<-PlotVolcano(mSet, "volcano_1_",1, "png", 72, width=NA)
mSet<-Volcano.Anal(mSet, FALSE, 1.5, 0, 0.75,T, 0.1, TRUE, "fdr")
mSet<-PlotVolcano(mSet, "volcano_2_",1, "png", 72, width=NA)
mSet<-PLSR.Anal(mSet, reg=TRUE)
mSet<-PlotPLSPairSummary(mSet, "pls_pair_0_", "png", 72, width=NA, 5)
mSet<-PlotPLS2DScore(mSet, "pls_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0)
mSet<-PlotPLS3DScoreImg(mSet, "pls_score3d_0_", "png", 72, width=NA, 1,2,3, 40)
mSet<-PlotPLSLoading(mSet, "pls_loading_0_", "png", 72, width=NA, 1, 2);
mSet<-PlotPLS3DLoading(mSet, "pls_loading3d_0_", "json", 1,2,3)
mSet<-PLSDA.CV(mSet, "T",5, "Q2")
mSet<-PlotPLS.Classification(mSet, "pls_cv_0_", "png", 72, width=NA)
mSet<-PlotPLS.Imp(mSet, "pls_imp_0_", "png", 72, width=NA, "vip", "Comp. 1", 15,FALSE)
mSet<-PLSDA.Permut(mSet, 100, "bw")
mSet<-PlotPLS.Permutation(mSet, "pls_perm_1_", "png", 72, width=NA)
mSet<-PLSDA.Permut(mSet, 100, "accu")
mSet<-PlotPLS.Permutation(mSet, "pls_perm_2_", "png", 72, width=NA)
mSet<-PLSDA.Permut(mSet, 1000, "accu")
mSet<-PlotPLS.Permutation(mSet, "pls_perm_3_", "png", 72, width=NA)
mSet<-PLSDA.Permut(mSet, 1000, "bw")
mSet<-PlotPLS.Permutation(mSet, "pls_perm_4_", "png", 72, width=NA)
