mSet<-InitDataObjects("conc", "stat", FALSE)
mSet<-Read.TextData(mSet, "Replacing_with_your_file_path", "rowu", "disc");
mSet<-SanityCheckData(mSet)
mSet<-ReplaceMin(mSet);
mSet<-FilterVariable(mSet, "rsd", "F", 25)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "QuantileNorm", "CrNorm", "NULL", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_0_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_0_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, F, 0.05, "fisher", FALSE)
mSet<-PlotANOVA(mSet, "aov_0_", "png", 72, width=NA)
mSet<-PlotCmpdView(mSet, "P02790", "png", 72, width=NA)
mSet<-PlotCmpdView(mSet, "G3XAM2", "png", 72, width=NA)
mSet<-PlotCmpdView(mSet, "P19440", "png", 72, width=NA)
mSet<-PlotCmpdView(mSet, "O75629", "png", 72, width=NA)
mSet<-PlotCmpdView(mSet, "P02790", "png", 72, width=NA)
mSet<-PlotCmpdView(mSet, "G3XAM2", "png", 72, width=NA)
mSet<-PlotCmpdView(mSet, "P27797", "png", 72, width=NA)
mSet<-PlotCmpdSummary(mSet, "O75629", 0, "png", 72, width=NA)
mSet<-PlotCmpdSummary(mSet, "P27797", 1, "png", 72, width=NA)
mSet<-PLSR.Anal(mSet, reg=TRUE)
mSet<-PlotPLSPairSummary(mSet, "pls_pair_0_", "png", 72, width=NA, 5)
mSet<-PlotPLS2DScore(mSet, "pls_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0)
mSet<-PlotPLS3DScoreImg(mSet, "pls_score3d_0_", "png", 72, width=NA, 1,2,3, 40)
mSet<-PlotPLSLoading(mSet, "pls_loading_0_", "png", 72, width=NA, 1, 2);
mSet<-PlotPLS3DLoading(mSet, "pls_loading3d_0_", "json", 1,2,3)
mSet<-PLSDA.CV(mSet, "T",5, "Q2")
mSet<-PlotPLS.Classification(mSet, "pls_cv_0_", "png", 72, width=NA)
mSet<-PlotPLS.Imp(mSet, "pls_imp_0_", "png", 72, width=NA, "vip", "Comp. 1", 15,FALSE)
mSet<-PLSDA.Permut(mSet, 100, "bw")
mSet<-PlotPLS.Permutation(mSet, "pls_perm_1_", "png", 72, width=NA)
mSet<-PLSDA.Permut(mSet, 1000, "bw")
mSet<-PlotPLS.Permutation(mSet, "pls_perm_2_", "png", 72, width=NA)
mSet<-PLSDA.Permut(mSet, 1000, "accu")
mSet<-PlotPLS.Permutation(mSet, "pls_perm_3_", "png", 72, width=NA)
mSet<-PreparePrenormData(mSet)
mSet<-Normalization(mSet, "QuantileNorm", "CrNorm", "RangeNorm", ratio=FALSE, ratioNum=20)
mSet<-PlotNormSummary(mSet, "norm_1_", "png", 72, width=NA)
mSet<-PlotSampleNormSummary(mSet, "snorm_1_", "png", 72, width=NA)
mSet<-PLSR.Anal(mSet, reg=TRUE)
mSet<-PlotPLSPairSummary(mSet, "pls_pair_0_", "png", 72, width=NA, 5)
mSet<-PlotPLS2DScore(mSet, "pls_score2d_0_", "png", 72, width=NA, 1,2,0.95,0,0)
mSet<-PlotPLS3DScoreImg(mSet, "pls_score3d_0_", "png", 72, width=NA, 1,2,3, 40)
mSet<-PlotPLSLoading(mSet, "pls_loading_0_", "png", 72, width=NA, 1, 2);
mSet<-PlotPLS3DLoading(mSet, "pls_loading3d_0_", "json", 1,2,3)
mSet<-PLSDA.CV(mSet, "T",5, "Q2")
mSet<-PlotPLS.Classification(mSet, "pls_cv_0_", "png", 72, width=NA)
mSet<-PlotPLS.Imp(mSet, "pls_imp_0_", "png", 72, width=NA, "vip", "Comp. 1", 15,FALSE)
mSet<-PLSDA.Permut(mSet, 100, "bw")
mSet<-PlotPLS.Permutation(mSet, "pls_perm_4_", "png", 72, width=NA)
mSet<-PLSDA.Permut(mSet, 100, "accu")
mSet<-PlotPLS.Permutation(mSet, "pls_perm_5_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, F, 0.05, "fisher", FALSE)
mSet<-PlotANOVA(mSet, "aov_0_", "png", 72, width=NA)
mSet<-ANOVA.Anal(mSet, F, 0.05, "fisher", FALSE)
mSet<-PlotANOVA(mSet, "aov_1_", "png", 72, width=NA)
mSet<-PLSDA.Permut(mSet, 1000, "bw")
mSet<-PlotPLS.Permutation(mSet, "pls_perm_6_", "png", 72, width=NA)
mSet<-PLSDA.Permut(mSet, 1000, "accu")
mSet<-PlotPLS.Permutation(mSet, "pls_perm_7_", "png", 72, width=NA)
mSet<-PLSDA.CV(mSet, "L",5, "Q2")
mSet<-PlotPLS.Classification(mSet, "pls_cv_1_", "png", 72, width=NA)
